version: '3.9'
services:
  backend:
    image: node:16.14-alpine
    container_name: backend
    ports:
      - 3001:3001
    working_dir: /src
    volumes: 
      - ./src:/src
    depends_on: 
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=1234
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    restart: 'always'